name: "Run system tests"
description: "Run system tests"
author: "andreas.jonsson@qlik.com"

inputs:
  suite:
    description: "Test suite to run"
    required: false
  import-map-overrides:
    description: "Import-map overrides to use e.g as a JSON string or URL to import-map"
    required: false
  docker-image:
    description: "Docker image to use"
    required: true
  docker-username:
    description: "Docker user name"
    required: true
  docker-password:
    description: "Docker password"
    required: true
  grid-url:
    description: 'Zalenium grid to use'
    required: false
  parallel-execution: 
    description: 'Number of parallell webdrivers to use'
    required: false
  base-url:
    description: "Url to test environment"
    required: true
  auth-url: 
    description: "Auth url to test environment"
    required: false
runs:
  using: "composite"
  steps:
  - run: |
      ${{ github.action_path }}/run-system-test.sh
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}
      GITHUB_WORKSPACE: ${{ github.workspace }}
      SUITE: ${{ inputs.suite }}
      QMFE_OVERRIDE: ${{ inputs.import-map-overrides }}
      WDURL: ${{ inputs.grid-url }}
      PARALLELEXECUTION: ${{ inputs.parallel-execution }}
      BASEURL: ${{ inputs.base-url }}
      AUTHURL: ${{ inputs.auth-url }}
      IMAGE: ${{ inputs.docker-image }} 
      DOCKER_USERNAME: ${{ inputs.docker-username }}
      DOCKER_PWD: ${{ inputs.docker-password }}
    shell: bash
