name: sync main branch to current version branch
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Merge main -> v1
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: main
          target_branch: v1
          commit_message_template: "[Automated] merge {source_ref} -> {target_branch}"
