name: Test QMFE Actions
on: push
jobs:
  qmfe-to-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create dist folder
        run: |
          mkdir dist
          echo "Running $GITHUB_WORKFLOW:$GITHUB_JOB:$GITHUB_RUN_NUMBER" > ./dist/run
          echo "FileOne" > ./dist/file1
          echo "FileTwo" > ./dist/file2
      - name: Test qmfe-to-aws action
        uses: qlik-oss/qmfe-actions/qmfe-to-aws@v1
        with:
          aws-bucket-name: qcs-stage-cdn.qlikcloud.com
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          qmfe-id: "test"
          version: "1.2.3"
          source: ./dist
          dry-run: "true"
          cache-control: "no-cache"
      - name: Test qmfe-to-aws action with files
        uses: qlik-oss/qmfe-actions/qmfe-to-aws@v1
        with:
          aws-bucket-name: qcs-stage-cdn.qlikcloud.com
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: ./dist
          qmfe-id: "test"
          version: "1.2.4"
          files: "file1,file2"
          dry-run: "true"
          cache-control: "no-cache"
  remove-cancelled-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Test remove-cancelled-workflow action
        uses: qlik-oss/qmfe-actions/remove-cancelled-workflow@v1
        with:
          repository: qlik-oss/qmfe-actions
          workflow-name: test-actions
          github-token: ${{ github.token }}
  import-map-to-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create import-map
        run: |
          echo '{"imports":{"@qmfe/startup":"https://cdn.qlik-stage.com/qmfe/main-web-container/0.22.0/qmfe-startup.js"}}' > ./import-map.json
      - name: Test import-map-to-aws action
        uses: qlik-oss/qmfe-actions/import-map-to-aws@generate-metrics
        with:
          aws-bucket-name: qcs-stage-cdn.qlikcloud.com
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-distribution-id: ${{ secrets.AWS_DISTRIBUTION_ID }}
          import-map-url: "https://cdn.qlik-stage-com/qmfe/import-map.json"
          dry-run: "true"
  update-qmfe-import-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create fake import-map
        run: |
          echo '{"imports":{"@qmfe/foo":"https://my-cdn.com/qmfe/foo/1.2.3/qmfe-foo.js"}}' > ./import-map.json
      - name: Test update-qmfe-import-map action
        uses: qlik-oss/qmfe-actions/update-qmfe-import-map@v1
        with:
          version: 1.2.3
          qmfe-id: test
          namespace: qlik-trial
          qmfe-modules: '["foo", "bar"]'
          github-team: my-org/some-team
          github-token: my-secret-token
          github-org: qlik-trial
          github-repo: qmfe-integration
          cdn-base-path: https://my-cdn.com
          dry-run: "true"
